-- CareCost Fusion — result tables in the dedicated demo schema.
-- DB/schema/warehouse already exist (see TEARDOWN.md). TRANSIENT tables: no fail-safe, lower cost.
USE WAREHOUSE CARECOST_WH;
USE SCHEMA CARECOST_DEMO.ANALYTICS;

CREATE OR REPLACE TRANSIENT TABLE RAW_CLAIMS (
    CLAIM_ID STRING,
    MEMBER_ID STRING,
    SERVICE_DATE DATE,
    CLAIM_TYPE STRING,
    DIAGNOSIS_GROUP STRING,
    PROVIDER_ID STRING,
    PAID_AMOUNT FLOAT,
    INPATIENT_FLAG INTEGER,
    ED_FLAG INTEGER
);

CREATE OR REPLACE TRANSIENT TABLE MODEL_PREDICTIONS (
    RUN_ID STRING,
    MODEL_TYPE STRING,
    MEMBER_ID STRING,
    INDEX_DATE DATE,
    ACTUAL_COST FLOAT,
    PREDICTED_COST FLOAT,
    RESIDUAL FLOAT,
    ABSOLUTE_ERROR FLOAT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TRANSIENT TABLE RESIDUAL_SUMMARY (
    RUN_ID STRING,
    SEGMENT_ID STRING,
    SEGMENT_DESCRIPTION STRING,
    MEMBER_COUNT INTEGER,
    MEAN_ACTUAL_COST FLOAT,
    MEAN_PREDICTED_COST FLOAT,
    MEAN_RESIDUAL FLOAT,
    MEAN_ABSOLUTE_ERROR FLOAT,
    SEGMENT_EVIDENCE VARIANT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TRANSIENT TABLE EXPERIMENT_RESULTS (
    RUN_ID STRING,
    PARENT_RUN_ID STRING,
    RUN_TYPE STRING,
    FEATURE_NAME STRING,
    FEATURE_SPEC VARIANT,
    MAE FLOAT,
    RMSE FLOAT,
    RMSLE FLOAT,
    HIGH_COST_RECALL FLOAT,
    MAE_IMPROVEMENT_PCT FLOAT,
    DECISION STRING,
    DECISION_REASON STRING,
    GEMINI_HYPOTHESIS STRING,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
